{% set name = "adc-streaming" %}
{% set version = "2.3.0" %}
{% set sha256 = "1ef60d1811e23eecdac4b1e425c0e9cf120a43753a6b6f98fe355d730f1671b5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adc-streaming-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm

  run:
    - python >=3.6
    - authlib
    - certifi >=2020.04.05.1
    - dataclasses
    - importlib-metadata
    - python-confluent-kafka
    - requests
    - tqdm
    - typing-extensions ; python_version < 3.8

test:
  imports:
    - adc

about:
  home: https://github.com/astronomy-commons/adc-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Astronomy Data Commons Streaming Client Library'
  description: |
    This package installs the ADC Streaming Client library

extra:
  recipe-maintainers:
    - adambrazier
    - mjuric
    - cnweaver
    - myNameIsPatrick
    - spenczar
