{% set name = "adc-streaming" %}
{% set version = "2.6.0" %}
{% set sha256 = "d0fcc076499980108701660ff5bfbe6d2a8d421e54380d6d86e9bfc870e731cc" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}
{% set python_min = python_min | default("3.6") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adc_streaming-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
    - setuptools-scm

  run:
    - python >={{ python_min }}
    - authlib
    - certifi >=2020.04.05.1
    - dataclasses
    - importlib-metadata
    - python-confluent-kafka
    - requests
    - tqdm
    - typing-extensions

test:
  imports:
    - adc

about:
  home: https://github.com/astronomy-commons/adc-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Astronomy Data Commons Streaming Client Library
  description: |
    This package installs the ADC Streaming Client library

extra:
  recipe-maintainers:
    - adambrazier
    - mjuric
    - cnweaver
    - myNameIsPatrick
    - spenczar
